############
# Don't be overwhelmed!
# The options are all provided so that hunting down the correct option for a given version of Zola for which the theme and config was tested can get more overwhelming.
# This way you now have a snapshot of all the options.
# For a quick look of all the changes made specifically for this website, you can diff it with the config.toml source link below. 
# https://github.com/getzola/zola/blob/b5236773820015712cbd5f7e82ea33fb5d1297db/docs/content/documentation/getting-started/configuration.md
############

# The base URL of the site; the only required configuration variable.
base_url = "http://siddhantladdha.com/draczola-bear/"

# The site title and description; used in feeds by default.
title = "Draczola  ï‚Ä¢·¥•‚Ä¢ î Blog"
description = "A Zola-theme based on Bear Blog in Dracula colors (A universal dark theme)"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "draczola-bear"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# Whether dotfiles at the root level of the output directory are preserved when (re)building the site.
# Enabling this also prevents the deletion of the output folder itself on rebuilds.
preserve_dotfiles_in_output = false

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = false

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = []

# Similar to ignored_content, a list of glob patterns specifying asset files to
# ignore when the static directory is processed. Defaults to none, which means
# that all asset files are copied over to the `public` directory
ignored_static = []

# When set to "true", a feed is automatically generated.
generate_feeds = false

# When set to "all", paginated pages are not a part of the sitemap, default is "none"
exclude_paginated_pages_in_sitemap = "none"

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
# feed_limit = 20

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
hard_link_static = false

# The default author for pages
author = "Vlad Dracula"

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]
# Optional base path for all taxonomies. If set, all taxonomy paths will be relative to this path.
# For example, if taxonomy_root is "blog" and taxonomy is "tags", the path will be /blog/tags/
# taxonomy_root = "blog"

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

# When set to "false", Sitemap.xml is not generated
generate_sitemap = true

# When set to "false", robots.txt is not generated
generate_robots_txt = true

# Configuration of the Markdown rendering
[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => üòÑ)
render_emoji = false

# CSS class to add to external links (e.g. "external-link")
external_links_class = ""

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

# Whether to set rel="external" for all external links
external_links_external = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `‚Ä¶`, `"quote"` into `‚Äúcurly‚Äù` etc
smart_punctuation = false

# Whether parsing of definition lists is enabled
definition_list = false

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isn‚Äôt ok
lazy_async_image = false

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = false

# When set to "true", support for GitHub-style alerts, a.k.a. callouts or admonitions, is enabled in the Markdown parser.
# For example, this Markdown syntax:
#
#     > [!NOTE]
#     > alert note
#
# will result in the following generated HTML:
#
#     <blockquote class="markdown-alert-note">
#     <p>alert note</p>
#     </blockquote>
#
# where the CSS class name suffix may be `note`, `tip`, `important`, `warning`, or `caution`, depending on the alert type.
# Visual appearance depends on theme-level support; refer to your theme's documentation for more information.
github_alerts = false

# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "none"

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = true

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = "dracula"

# 2. If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting page for the possible choices.
light_theme = ""
dark_theme = ""

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
extra_themes = []

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "http://[2001:db8::]/",
]

# Skip anchor checking for external URLs that start with these prefixes
skip_anchor_prefixes = [
    "https://caniuse.com/",
]

# Treat internal link problems as either "error" or "warn", default is "error"
internal_level = "error"

# Treat external link problems as either "error" or "warn", default is "error"
external_level = "error"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
paths_keep_dates = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the RFC3339 datetime of the page in the search index
include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Whether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
index_format = "elasticlunr_javascript"

# Optional translation object for the default language
# Example:
#     default_language = "fr"
#
#     [translations]
#     title = "Un titre"
#
[translations]
# Additional languages definition
# You can define language specific config values and translations:
# title, description, generate_feeds, feed_filenames, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"
[languages]
# For example
# [languages.fr]
# title = "Mon blog"
# generate_feeds = true
# taxonomies = [
#    {name = "auteurs"},
#    {name = "tags"},
# ]
# build_search_index = false
[languages.de]
title = "Zola  ï‚Ä¢·¥•‚Ä¢ î Bear Blog"
description = "Ein Zola-Thema basierend auf Bear Blog in Dracula-Farben (ein universelles dunkles Thema)"
taxonomies = [
  { name = "kategorien", feed = true },
  { name = "schilder", feed = true },
]
[languages.de.translations]
no_posts = "Keine Eintr√§ge"
remove_filter = "Filter entfernen"
filtering_for = "Filtern nach"
made_with = "Erstellt mit"
table_of_contents = "Inhaltsverzeichnis"
language = "Sprache"
site = "Site"
# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     author = "Famous author"
#
# author value will be available using {{ config.extra.author }} in templates
#
[extra]
# Defaults are taken from theme.toml
date_format = "%Y-%m-%d"
webserver_sends_csp_headers = false
[extra.table_of_contents]
show = true
max_level = 3
visible_on_load = false
# Choose color scheme: "dracula" (default), "alucard"
color_scheme = "dracula"
language_switcher = true
translations = [
  { code = "en", name = "English" },
  { code = "de", name = "Deutsch" },
]
# Change to true to
# hide made with line.
hide_made_with_line = false
# Currently only CC BY-NC-SA supported. 
show_copyright_in_footer = true

# These are extra keys which are specific to this theme's layout.
# You can essentially see that they show up on the header. 
# Create an array in extra with a key of main_menu. url is passed to [get_url](https://www.getzola.org/documentation/templates/overview/#get-url)
[[extra.main_menu]]
name = "Home"
name_de = "Startseite"
url = "@/_index.md"

[[extra.main_menu]]
name = "Bear"
name_de = "Bear"
url = "@/bear.md"

[[extra.main_menu]]
name = "Zola"
name_de = "Zola"
url = "@/zola.md"

[[extra.main_menu]]
name = "Blog"
name_de = "Blog"
url = "@/blog/_index.md"