name = "Draczola Bear"
description = "Bear enters the darkness"
license = "MIT"
homepage = "https://github.com/siddhantladdha/draczola-bear"
# The minimum version of Zola required
min_version = "0.22.0"
# An optional live demo URL
demo = "https://sid555.com/draczola-bear/"

# Any variable below can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
date_format = "%Y-%m-%d"
webserver_sends_csp_headers = false
# Choose color scheme: "dracula" (default), "alucard"
color_scheme = "dracula"
language_switcher = true
translations = [
  { code = "en", name = "English" },
  { code = "de", name = "Deutsch" },
]
# Change to true to
# hide made with line.
hide_made_with_line = false
show_copyright_in_footer = true
[extra.table_of_contents]
show = true
max_level = 3
visible_on_load = false

[author]
name = "Siddhant Laddha"
homepage = "https://siddhantladdha.com"

[original]
name = "Alan Pearce"
homepage = "https://alanpearce.eu"
repo = "https://codeberg.org/alanpearce/zola-bearblog"
